using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BanderaCanada.Clases
{
    class Bandera
    {
        public void Mostrar()
        {
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine("                                    Esta es la bandera de Cánanda");

            Console.ReadLine();
            Console.Clear();

            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.WriteLine("***");
            Console.WriteLine("*****");
            Console.WriteLine("*****");
            Console.WriteLine("***");
            Console.Write("::::  ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(" , , , , , , , , , , , , , , ,");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" , , , , , , , , , , , ,");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write("::: ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(" ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::  ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ;");

            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::  ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(":'':");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::  ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(":::");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(";; ;;; ;;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(":::");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ;");

            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::  ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(";;;;;;;;;;;;;;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ;");

            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::  ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(":::");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("`;;;;;;;;;;;;'");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(":::");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ;");

            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::  ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(":::; ;::");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(".;;;;;;;;;.");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("::; ;:::");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ;");

            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::  ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(";;;;;;;;:");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(";;;;;;;;;;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("/;;;;;;;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ;");

            //M
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::  ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("<;;;;;;;;;;;;;;;';;;;;;;;>");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::  ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(":;;;;;;;;;;;;;;;;;;;;;/");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ; ");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::  ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("::;;;;;;;;;;;;;;::");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ; ");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::  ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write("; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(":; ; ;;; ; ;:");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ; ");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write("::: /");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(" ' ' ' ; ; ; ; ; ; ; ; ; ; ; ; ; ");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(";;;");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write(" @@@@@@@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ; ");

            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::/        ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(" ' ' ' : : ; ; ; ; ; ; ; ; ");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Write(";");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("@@@@@@@@@@@@@@@@@@@");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(" ; ; ; ; ; ; ; ; ; ; ; ; ");


            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::                                             ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine("              ");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::                                             ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine("              ");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(":::                                             ");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine("             ");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.WriteLine(":::");
            Console.WriteLine(":::");
            Console.WriteLine(":::");
            Console.WriteLine(":::");
            Console.WriteLine(":::");
            Console.WriteLine(":::");
            Console.WriteLine(":::");
            Console.WriteLine(":::");
            Console.WriteLine(":::");
            Console.WriteLine(":::");

            Console.WriteLine(":::::::");
            Console.WriteLine(":::::::");
            Console.WriteLine("=======");

            Console.Read();

        }
    }
}
